name: 'Setup GAP for package testing'
description: 'Download and compile CI scripts, GAP and its packages'
inputs:
  GAP_VERSION:
    description: 'The gap version or branch to use (default: latest release)'
    required: false
    default: 'latest'
  GAP_BOOTSTRAP:
    description: 'make bootstrap-pkg-? (i.e. full/minimal)'
    required: false
    default: 'full'
env:
  CHERE_INVOKING: 1
runs:
  using: "composite"
  steps:
      - name: "Install dependencies"
        run: |
          echo "Installing dependencies"
          if [ "${{runner.os}}" = "Linux" ]; then
            packages=(
              libgmp-dev
              libreadline-dev
              zlib1g-dev
            )
            sudo apt-get install "${packages[@]}"
          elif [ "${{runner.os}}" = "macOS" ]; then
            brew install gmp zlib autoconf && brew link zlib
          fi
        shell: bash

      - name: "Clone GAP"
        shell: bash
        run: |
          VERSION=""
          IS_TAG=true
          GIT_TAGS=$(git ls-remote --tags --refs https://github.com/gap-system/gap.git | sed 's|.*refs/tags/||')
          GIT_BRANCHES=$(git ls-remote --heads https://github.com/gap-system/gap.git | sed 's|.*refs/heads/||')
          LATEST_TAG=$(echo "$GIT_TAGS" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          DEFAULT_BRANCH=$(git ls-remote --symref https://github.com/gap-system/gap.git HEAD | head -n 1 | sed 's|ref: refs/heads/||; s|\tHEAD||')
          if [[ "${{ inputs.GAP_VERSION }}" == "latest" ]] ; then
            VERSION=$LATEST_TAG
          elif echo "$GIT_TAGS" | grep -qx "${{ inputs.GAP_VERSION }}" ; then
            VERSION=${{ inputs.GAP_VERSION }}
          elif echo "$GIT_TAGS" | grep -qx "v${{ inputs.GAP_VERSION }}" ; then
            VERSION=v${{ inputs.GAP_VERSION }}
          elif [[ "${{ inputs.GAP_VERSION }}" == "default" ]] ; then
            VERSION=$DEFAULT_BRANCH
            IS_TAG=false
          elif echo "$GIT_BRANCHES" | grep -qx "${{ inputs.GAP_VERSION }}" ; then
            VERSION=${{ inputs.GAP_VERSION }}
            IS_TAG=false
          else
            echo "No branch or tag with name $GAP_VERSION found"
            exit 1
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "IS_TAG=$IS_TAG" >> "$GITHUB_ENV"
          git clone --branch $VERSION --depth=1 --single-branch https://github.com/gap-system/gap.git $HOME/gap

      - name: "Build GAP"
        shell: bash
        run: |
          cd $HOME/gap
          CONFIGFLAGS="${{ inputs.CONFIGFLAGS }}"

          # build GAP in a subdirectory
          ./autogen.sh
          ./configure $CONFIGFLAGS
          make -j4 V=1

          # make it available
          ln -s $HOME/gap/gap /usr/local/bin/gap
          chmod +x /usr/local/bin/gap

      - name: "Download packages"
        shell: bash
        run: |
          cd $HOME/gap

          # download packages; instruct wget to retry several times if the
          # connection is refused, to work around intermittent failures.
          # for older versions, set WGET, for GAP >= 4.11 set DOWNLOAD
          WGET="wget -N --no-check-certificate --tries=5 --waitretry=5 --retry-connrefused"
          
          if [[ "${{ env.IS_TAG }}" == "true" ]] ; then
            if [[ "${{ inputs.GAP_BOOTSTRAP }}" == "minimal" ]] ; then
              MINIMAL="-required"
            fi
            echo "ITS A TAG"
            URL=https://github.com/gap-system/gap/releases/download/${{ env.VERSION }}/
            FILE=packages$MINIMAL-${{ env.VERSION }}.tar.gz
            $WGET $URL$FILE
            mkdir pkg
            tar xzf $FILE -C pkg
          else
            echo "ITS A BRANCH"
            make bootstrap-pkg-${{ inputs.GAP_BOOTSTRAP }} DOWNLOAD="$WGET" WGET="$WGET"
          fi
          
      - name: "Quick test"
        shell: bash
        run: |
          gap -c "LoadAllPackages();QuitGap();"
