name: 'Setup GAP for package testing'
description: 'Download and compile GAP and its packages'
inputs:
  gap-version:
    description: 'The GAP version or branch to use (default: latest release)'
    required: false
    default: 'latest'
  repository:
    description: 'The GitHub repository from which to clone GAP (default: gap-system/gap)'
    required: false
    default: 'gap-system/gap'
  configflags:
    description: 'Arguments to pass to the GAP configure script (e.g. --enable-debug)'
    required: false
    default: ''
  gap-pkgs-to-build:
    description: 'A space-separated list of the GAP packages to build'
    required: false
    default: 'io json profiling'
    deprecationMessage: 'This input will possibly be removed in the future, so do not rely on it too much'

runs:
  using: "composite"
  steps:
  
    - name: "Install dependencies"
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          sudo apt-get install libgmp-dev libreadline-dev zlib1g-dev
        elif [[ "${{ runner.os }}" = "macOS" ]] ; then
          brew install zlib autoconf && brew link zlib --force
        fi

    - name: "Determine GAP version"
      shell: bash
      run: |
        VERSION=""
        IS_RELEASE=false

        # Get all tags, branches and (hopefully) releases
        # Avoid using the GitHub API since it is rather strongly rate-limited...
        GIT_TAGS=$(git ls-remote --tags --refs https://github.com/${{ inputs.repository }}.git | sed 's|.*refs/tags/||')
        GIT_BRANCHES=$(git ls-remote --heads https://github.com/${{ inputs.repository }}.git | sed 's|.*refs/heads/||')

        # Select only those releases we wish to allow, with or without pre-releases
        GIT_RELS=$(echo "$GIT_TAGS" | egrep '^v[0-9]+\.[0-9]+\.[0-9]*' | sort -V)
        GIT_RELSALL=${GIT_RELS#*v4.9.3}
        GIT_RELSFIN=$(echo "$GIT_RELSALL" | egrep '^v[0-9]+\.[0-9]+\.[0-9]+$')

        if [[ "${{ inputs.gap-version }}" =~ ^(|latest)$ ]] ; then
          # Get tag of latest (non-pre-)release
          IS_RELEASE=true
          VERSION=$(echo "$GIT_RELSFIN" | tail -n 1)
        elif [[ "${{ inputs.gap-version }}" =~ ^(master|main|default)$ ]] ; then
          # Get default branch from git
          VERSION=$(git ls-remote --symref https://github.com/${{ inputs.repository }}.git HEAD | head -n 1 | sed 's|ref: refs/heads/||; s|\tHEAD||')
        elif echo "$GIT_BRANCHES" | grep -qx "${{ inputs.gap-version }}" ; then
          # Exact branch match
          VERSION=${{ inputs.gap-version }}
        else
          IS_RELEASE=true
          # We now try to match with releases
          # Add "v" in front if missing
          REL=${{ inputs.gap-version }}
          REL=v${REL#v}
          if echo "$GIT_RELSALL" | grep -qx "$REL" ; then
            # Exact release match
            VERSION=$REL
          else
            # Expand tag to latest (non-pre-)release
            VERSION=$(echo "$GIT_RELSFIN" | grep "^$REL\." | tail -n 1)
          fi
        fi
          
        if [ -z $VERSION ] ; then
          echo "No branch or release with name ${{ inputs.gap-version }} found"
          exit 1
        fi
        echo "VERSION=$VERSION" >> "$GITHUB_ENV"
        echo "IS_RELEASE=$IS_RELEASE" >> "$GITHUB_ENV"

    - name: "Set GAPROOT"
      shell: bash
      run: |
        GAPROOT=$HOME/gap
        mkdir -p $GAPROOT
        echo "GAPROOT=$GAPROOT" >> "$GITHUB_ENV"
        
    - name: "Download or clone GAP"
      shell: bash
      run: |
        if [[ "$IS_RELEASE" == "true" ]] ; then
          WGET="wget -q -N --no-check-certificate --tries=5 --waitretry=5 --retry-connrefused"
          URL=https://github.com/${{ inputs.repository }}/releases/download/$VERSION/
          FILE=gap-${VERSION#v}.tar.gz
          $WGET $URL$FILE
          tar xzf $FILE -C $GAPROOT --strip-components=1
        else
          git clone --branch $VERSION --depth=1 --single-branch https://github.com/${{ inputs.repository }}.git $GAPROOT
        fi

    - name: "Build GAP"
      shell: bash
      run: |
        cd $GAPROOT

        if [ -f "autogen.sh" ] ; then
          ./autogen.sh
        fi
        ./configure "${{ inputs.configflags }}"
        make -j4 V=1

        # Add to PATH
        if [ -f "$GAPROOT/gap" ] ; then
          ln -s $GAPROOT/gap /usr/local/bin/gap
        else
          echo -e '#!/bin/sh\nsh '"$GAPROOT"'/bin/gap.sh "$@"\n' > /usr/local/bin/gap
        fi

        # Just to be sure it's executable
        chmod +x /usr/local/bin/gap

    - name: "Download GAP packages"
      shell: bash
      run: |
        cd $GAPROOT
        if [[ "$IS_RELEASE" == "false" ]] ; then
          WGET="wget -q -N --no-check-certificate --tries=5 --waitretry=5 --retry-connrefused"
          make bootstrap-pkg-full DOWNLOAD="$WGET" WGET="$WGET"
        fi

    - name: "Build GAP packages"
      shell: bash
      run: |
        BuildPackagesOptions="--strict"
        shopt -s nocaseglob
        cd $GAPROOT/pkg
        for pkg in ${{ inputs.gap-pkgs-to-build }}; do
            ../bin/BuildPackages.sh ${BuildPackagesOptions} $pkg*
        done
