name: 'Setup GAP for package testing'
description: 'Download and compile GAP and its packages'
inputs:
  gap-version:
    description: 'The GAP version or branch to build'
    required: false
    default: 'latest'
  repository:
    description: 'The GitHub repository from which to clone GAP'
    required: false
    default: 'gap-system/gap'
  configflags:
    description: 'Arguments to pass to the GAP configure script (e.g. --enable-debug)'
    required: false
    default: ''
  gap-pkgs-to-build:
    description: 'A space-separated list of the GAP packages to build'
    required: false
    default: 'io json profiling'
    deprecationMessage: 'This input will possibly be removed in the future, so do not rely on it too much'

runs:
  using: "composite"
  steps:
  
    - name: "Install dependencies"
      shell: bash
      if: ${{ runner.os != 'Windows' }}
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          sudo apt-get install libgmp-dev libreadline-dev zlib1g-dev
        elif [[ "${{ runner.os }}" = "macOS" ]] ; then
          brew install zlib autoconf && brew link zlib --force
        fi

    - name: "Determine GAP version"
      id: version
      shell: bash
      run: |
        VERSION=""
        IS_RELEASE=true

        # We only check for releases in the official repository
        if [[ "${{ inputs.repository }}" == "gap-system/gap" ]] ; then
          wget -q -O $RUNNER_TEMP/gap_releases.json "https://raw.githubusercontent.com/Joseph-Edwards/GapWWW/refs/heads/add-json/_data/gap_releases.json" 
          if [[ "${{ inputs.gap-version }}" == "latest" ]] ; then
            echo "Version: latest release"
            VERSION=$(cat $RUNNER_TEMP/gap_releases.json | jq -r '.[] | select(.isLatest == true) | .tagName ')
          else
            echo "Checking releases"
            GIT_RELS=$(cat $RUNNER_TEMP/gap_releases.json | jq -r '.[].tagName' | sort -V)
            GIT_NPRS=$(cat $RUNNER_TEMP/gap_releases.json | jq -r '.[] | select(.isPrerelease == false) | .tagName' | sort -V)

            # Add "v" in front if missing
            REL=${{ inputs.gap-version }}
            REL=v${REL#v}

            if echo "$GIT_RELS" | grep -qx "$REL" ; then
              echo "Version: exact release match"
              VERSION=$REL
            elif echo "$GIT_NPRS" | grep -q "^$REL\." ; then
              echo "Version: expanded to release"
              VERSION=$(echo "$GIT_NPRS" | grep "^$REL\." | tail -n 1)
            fi
          fi
        fi

        # If we use a different repo or didn't match a release, we try branches and tags instead
        if [[ -z "$VERSION" ]] ; then
          IS_RELEASE=false
          # Use the repository's default branch, or autocorrect to the default one if "master" or "main" was given
          if [[ "${{ inputs.gap-version }}" =~ ^(master|main|default)$ ]] ; then
            echo "Version: default branch"
            VERSION=$(git ls-remote --symref https://github.com/${{ inputs.repository }}.git HEAD | head -n 1 | sed 's|ref: refs/heads/||; s|\tHEAD||')
          elif git ls-remote --heads https://github.com/${{ inputs.repository }}.git | sed 's|.*refs/heads/||' | grep -qx "${{ inputs.gap-version }}" ; then
            echo "Version: exact branch match"
            VERSION=${{ inputs.gap-version }}
          elif git ls-remote --tags --refs https://github.com/${{ inputs.repository }}.git | sed 's|.*refs/tags/||' | grep -qx "${{ inputs.gap-version }}" ; then
            echo "Version: exact tag match"
            VERSION=${{ inputs.gap-version }}
          else
            echo "No release, branch or tag with name ${{ inputs.gap-version }} found"
            exit 1
          fi
        fi

        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
        echo "IS_RELEASE=$IS_RELEASE" >> "$GITHUB_OUTPUT"

    - name: "Set GAPROOT"
      shell: bash
      run: |
        GAPROOT="$HOME/gap"
        mkdir -p $GAPROOT
        echo "GAPROOT=$GAPROOT" >> "$GITHUB_ENV"
        
    - name: "Download or clone GAP"
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
        IS_RELEASE: ${{ steps.version.outputs.IS_RELEASE }}
      run: |
        if [[ "$IS_RELEASE" == "true" ]] ; then
          WGET="wget -q -N --no-check-certificate --tries=5 --waitretry=5 --retry-connrefused -O $RUNNER_TEMP/gap.tar.gz"
          URL=$(cat $RUNNER_TEMP/gap_releases.json | jq -r --arg VERSION "$VERSION" '.[] | select(.tagName == $VERSION) | .url ')
          SHA=$(cat $RUNNER_TEMP/gap_releases.json | jq -r --arg VERSION "$VERSION" '.[] | select(.tagName == $VERSION) | .sha256 ')
          # Download archive
          $WGET $URL
          # Recalculate checksum
          CHK=$(shasum -a 256 $RUNNER_TEMP/gap.tar.gz | awk '{print $1}')
          # Remove leading backslash if present, this can happen on Cygwin
          CHK=${CHK#\\}
          # Compare checksums
          if [[ "$SHA" != "$CHK" ]] ; then
            echo "Checksum is wrong!"
            exit 1
          fi
          # Extract archive
          tar xzf $RUNNER_TEMP/gap.tar.gz -C $GAPROOT --strip-components=1
        else
          git clone --branch $VERSION --depth=1 --single-branch https://github.com/${{ inputs.repository }}.git $GAPROOT
        fi

    - name: "Build GAP"
      shell: bash
      run: |
        cd $GAPROOT
        CONFIGFLAGS="${{ inputs.configflags }}"
        
        if [ -f "autogen.sh" ] ; then
          echo "::group:: Running autogen"
          ./autogen.sh
        fi

        if [[ "${{ runner.os }}" = "macOS" ]] ; then
          BP=$(brew --prefix)
          CONFIGFLAGS="--with-gmp=$BP --with-readline=$BP/opt/readline $CONFIGFLAGS"
        fi
        echo "::group:: Running configure with flags $CONFIGFLAGS"
        ./configure $CONFIGFLAGS

        echo "::group:: Running make"
        make -j4 V=1

        echo "::group:: Adding GAP to PATH"
        # Add to PATH
        if [ -f "$GAPROOT/gap" ] ; then
          ln -s $GAPROOT/gap /usr/local/bin/gap
        else
          echo -e '#!/bin/sh\nsh '"$GAPROOT"'/bin/gap.sh "$@"\n' > /usr/local/bin/gap
        fi

        # Just to be sure it's executable
        chmod +x /usr/local/bin/gap

    - name: "Download GAP packages"
      shell: bash
      if: ${{ steps.version.outputs.IS_RELEASE == 'false' }}
      run: |
        cd $GAPROOT
        WGET="wget -q -N --no-check-certificate --tries=5 --waitretry=5 --retry-connrefused"
        # For GAP >= 4.11 set DOWNLOAD, for older versions set WGET
        make bootstrap-pkg-full DOWNLOAD="$WGET" WGET="$WGET"

    - name: "Build GAP packages"
      shell: bash
      if: ${{ inputs.gap-pkgs-to-build  != '' }}
      run: |
        BuildPackagesOptions="--strict"
        shopt -s nocaseglob
        cd $GAPROOT/pkg
        for pkg in ${{ inputs.gap-pkgs-to-build }}; do
            ../bin/BuildPackages.sh ${BuildPackagesOptions} $pkg*
        done
