name: CI

# Trigger the workflow on push or pull request
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

env:
  CHERE_INVOKING: 1

jobs:
  test:
    name: ${{ matrix.gap-branch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gap-branch:
          - stable-4.7
          - 4.7.7
          - master
          - 4.14.0
          - 4.11.1
          - 4.11.0
          - 4.12.0
          - default
          - latest
        gap-bootstrap:
          - full
          - minimal

    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.os == 'windows-latest' }}
        uses: gap-actions/setup-cygwin@v1
      - uses: ./
        with:
          GAP_VERSION: ${{ matrix.gap-branch }}
          GAP_BOOTSTRAP: ${{ matrix.gap-bootstrap }}
