name: CI

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.gap-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        gap-version:
          - latest
          - v4
          - "4.10"
          - 4.11.0
          - v4.11.1
          - 4.12.0
          - v4.13.0-alpha2
          - 4.14.0-beta1
          - v4.14.0
          - stable-4.10
          - stable-4.12
          - stable-4.14
          - master
          - main
          - default

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Cygwin"
        if: ${{ matrix.os == 'windows-latest' }}
        uses: stertooy/setup-cygwin@official-action-and-batch
        
      - name: "Setup GAP"
        uses: ./
        with:
          gap-version: ${{ matrix.gap-version }}

      - name: "Run GAP"
        shell: bash
        run: |
          gap -A <<GAPINPUT
            FORCE_QUIT_GAP(LoadPackage("io") and LoadPackage("json") and LoadPackage("profiling"));
          GAPINPUT

      - name: "Check ENV for GAPROOT"
        shell: bash
        run: |
          echo $GAPROOT
          
      - name: "Check ARCH"
        shell: bash
        run: |
          gap <<GAPINPUT
            Print( "Unix: ", ARCH_IS_UNIX(), "\n" );
            Print( "macOS: ", ARCH_IS_MAC_OS_X(), "\n" );
            Print( "Windows: ", ARCH_IS_WINDOWS(), "\n" );
            Print( "WSL: ", ARCH_IS_WSL(), "\n" );
          GAPINPUT
