name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
      - cygwin*
  pull_request:

env:
  CHERE_INVOKING: 1

jobs:
  test:
    name: ${{ matrix.gap-branch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gap-branch:
          - master
          - 4.14.0
          - default
          - latest

    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.os == 'windows-latest' }}
        uses: gap-actions/setup-cygwin@v1
      - uses: ./
        with:
          GAP_VERSION: ${{ matrix.gap-branch }}
